version: '3.0'

services:

  app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: nest-docker
      ports:
        - '3000:3000'
      volumes:
        - ./src:/app/src